### ISSUE TITLE
能支持划词翻译吗？

### ISSUE THREAD

**Issue by Mrcooder** [wallenweel/weel-translate#13]
使用体验很好，插件非常美观，实用性很强，已经爱上了这款插件。
但是现在只能翻译句子，感觉很不方便，能增加划词翻译的选项吗？

**Comment by wallenweel** [comment]
是指直接高亮目标单词吗？

可以翻译单词或者句子，不想限制使用方式，所以就没有区别模式，就是选中什么翻译什么（双击文本选中单词、三击句子

如果是具体的特性的需求可以在评论或者github 上开个 issue，现在 57 正式版已经发布了，将来如果确定更新 v1.0 版的话会把现在积累下来的问题用更优雅的方式实现，现在的版本因为没想太多，没用任何类库，实现得太粗糙了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by Mrcooder** [comment]
就是想能够翻译段落，或者说翻译自己选中的文本，而不一定是单词或句子。

**Comment by wallenweel** [comment]
抱歉没太明白，现在的选中方式就是自己手动选文本，选了多少文本就翻译多少；

直接翻译段落这个一开始考虑过，但因为是用的别人免费翻译资源，事实上是借(dao)用它们的 API，担心用量高了之后会不稳定就作罢了，实际上可以自己手动选段落的，没做字数限制。

计划在 v1.0 版中完全开放这个接口，可以用户自己定制第三方的翻译接口，这个扩展就成个壳子，省的 api 变动后就要重新提交版本，火狐审核需要时间，现在个别的音标和翻译结果的不正常就是这个原因。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by Mrcooder** [comment]
虽然可以手动选择文本，但是翻译的内容始终就只有第一句话，不知道算不算 BUG - -




------------------ 原始邮件 ------------------
发件人: "wallen";<notifications@github.com>;
发送时间: 2017年11月17日(星期五) 晚上8:06
收件人: "wallenweel/weel-translation-extension"<weel-translation-extension@noreply.github.com>;
抄送: "mrcode"<734202639@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wallenweel/weel-translation-extension] 能支持划词翻译吗？ (#13)



抱歉没太明白，现在的选中方式就是自己手动选文本，选了多少文本就翻译多少； 
 
 直接翻译段落这个一开始考虑过，但因为是用的别人免费翻译资源，事实上是借(dao)用它们的 API，担心用量高了之后会不稳定就作罢了，实际上可以自己手动选段落的，没做字数限制。 
 
 计划在 v1.0 版中完全开放这个接口，可以用户自己定制第三方的翻译接口，这个扩展就成个壳子，省的 api 变动后就要重新提交版本，火狐审核需要时间，现在个别的音标和翻译结果的不正常就是这个原因。 
 
 发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用 
 
 ________________________________

**Comment by wallenweel** [comment]
果然，谷歌只翻译第一句，百度和有道是到第一个换行符为止😂，平常很少翻长段的，真没注意到，我先记下来了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by Mrcooder** [comment]
蛤蛤，感谢你的插件，用着很舒服~

**Comment by wallenweel** [comment]
新版中自带的翻译源接口已处理换行翻译问题，或者通过自定义翻译接口解决。
