### ISSUE TITLE
百度翻译引擎无音标显示

### ISSUE THREAD

**Issue by hbteng** [wallenweel/weel-translate#17]
界面漂亮，该有的功能都有，Firefox翻译插件中最好用的.

**Comment by wallenweel** [comment]
感谢给这么高的评价 ( •̀ ω •́ )✧

翻译源的结果是不可控的，不知道什么时候就变动了数据接口，毕竟是“借”用它们的接口，还没搞太清参数细节，像有的词有音标，有的偶尔会返回拼音什么的现象。

现在是跳过原来规划的 1.0 开发[2.0 正式版](https://github.com/wallenweel/weel-translate)，接口开放给用户，可以根据自己的喜好“组装”符合自己需求的结果，界面转用 vueify material ui 框架，会更漂亮一些，至少会有更多的过度动效了。

**Comment by wallenweel** [comment]
v2 版本中已支持自定义服务源和结果解析来规避此类问题。
