### ISSUE TITLE
Hide phonetic <div> if not defined in parser

### ISSUE THREAD

**Issue by ImJezze** [wallenweel/weel-translate#25]
If the "parser" element doesn't contain "phonetic_src" or "phonetic_dest" the corresponding \<div\> should be hidden in float panel.

**Comment by wallenweel** [comment]
I try to do this, but i think maybe the "voice request" button could be used sometimes, so I keep it but options to disabled them will be added in "Setting" part of popup in next version.

Thanks for your comment😀.

**Comment by ImJezze** [comment]
An option to disable them also sounds good. Thanks for your response.

**Comment by wallenweel** [comment]
Added in v2.0.3
