### ISSUE TITLE
Google中国 无法英文发音

### ISSUE THREAD

**Issue by zhouchengcom** [wallenweel/weel-translate#27]
Google中国 无法英文发音

**Comment by wallenweel** [comment]
源语言看下是否是 “自动”，谷歌不支持 发音自动识别语言（有道支持），选择对应语言后就可以了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by zhouchengcom** [comment]
可以了  100个赞 能移植到chrome吗

**Comment by wallenweel** [comment]
Chrome 对我来说是 WEB 开发担当，除了开发工具什么扩展都不装，日常基本不用 (*/ω＼*)，所以只对火狐的 web extension 接口熟悉一些；

不过写这个扩展的时候有注意在可能方便移植的地方做了处理（根据 MDN 的兼容表），比如把 browser 全局变量统一管理啥的，支持多 manifest 打包。

还有原因就是火狐的 web extension 接口感觉会慢慢和 chrome 差异化，平台间兼容已经和我开发第一版很更大的不同的，第一版的时候稍加改动就能在chrome 中加载调试，现在就不行了。

如果有人熟悉 chrome 扩展审核开发的话可以 fork 尝试，近期要考虑生活的问题和回归漫画的制作学习了，会逐渐放下开发工作，也许再之后有充足空闲时间的时候会做移植。

**Comment by zhouchengcom** [comment]
被开发耽误的漫画家 :blush:
