### ISSUE TITLE
使用右键菜单后页面浮动面板不会消失

### ISSUE THREAD

**Issue by kylingit** [wallenweel/weel-translate#28]
首先，在新的标签页直接右键翻译是不行的，得先选择一个词
选择一个词后右键翻译或者浮动按钮翻译，正常
然后取消选择单词，再使用右键翻译，这时弹出浮动面板，翻译的是刚刚选择的词，然后浮动面板就无法消失了。。。得另外选词或者刷新页面

Firefox 58.0b13  Windows 10 1709

**Comment by wallenweel** [comment]
嗯，要选中文本才能翻译；
翻译结束后貌似没有重置选中的文本（不怎么用右键没注意到，因为浮动按钮必须有文本被选中才会出现）；

之后版本中会改进一下这个部分。

如果了解 Vue 的话，临时解决办法可以在 选项页 的模板设置里 重写 Vue 选项的 watch 属性（把 `src/pages/content/defaultOptions.js` 中的 watch 复制到模板脚本部分，然后添加对 `loading` 的监听，值为 false 的时候设置 `this.selectedText = null`

**Comment by wallenweel** [comment]
v2.0.9 中已修复
