### ISSUE TITLE
Firefox Nightly（59.0a1）无法自动翻译

### ISSUE THREAD

**Issue by LoogCP** [wallenweel/weel-translate#30]
勾选“选中文本立即翻译”无法直接翻译，需要点击浮标才能出现翻译结果

**Comment by wallenweel** [comment]
没有针对测试过稳定版以外的版本，因为习惯原因，保持在了 56 版，刚刚试了下，在 56及57 可用；

也许是因为翻译延迟，google 在首次翻译的时候会比较慢，之后就很快了，稍微等待一下或者更换其他源尝试；

包括这个设置在内的一些设计普通网页的代码 需要刷新页面才能重新载入生效；

**Comment by LoogCP** [comment]
我写完这个之后，Firefox更新到了60，立即翻译有了。
另外想问一下，怎么翻译段落或者长句

在 2018年1月23日 下午5:53，wallen <notifications@github.com>写道：

**Comment by wallenweel** [comment]
等下回去会在其它电脑上安装测试版 (●'◡'●)

在弹出面板里时可以 ctrl + enter 换行，长句的话 google 是支持的。
