### ISSUE TITLE
在富文本编辑器中存在bug

### ISSUE THREAD

**Issue by quadimodo** [wallenweel/weel-translate#32]
两个地方碰见此bug
1. 公司oa系统中
2. 禅道评论中
ff 59.0b13
![error1](https://user-images.githubusercontent.com/22147006/36830650-7e71ff2c-1d5f-11e8-997c-c00bdcdab910.PNG)
![error2](https://user-images.githubusercontent.com/22147006/36830659-89b6b74c-1d5f-11e8-9656-4b5a671da7a2.PNG)

**Comment by wallenweel** [comment]
## 解决方法：
打开此类编辑页面前，在 **设置** 里临时关闭加载内容脚本。
![default](https://user-images.githubusercontent.com/11782913/36830843-4b70e754-1d60-11e8-86ae-8e0c72548423.png)

## 猜测原因：
扩展的内容脚本通过 manifest.json 扩展的配置加载到页面中的所有 iframe 中（因为许多第三方评论或者页面喜欢用 iframe 展示内容），而出现问题的富文本编辑器可能通过一个隐藏的 iframe 来存储所见即所得的 html 内容。

**Comment by wallenweel** [comment]
v2.3.2 中添加额外选项控制 iframe 的行为，默认不在 iframe 中加载
