### ISSUE TITLE
希望能尽快上架 Firefox 商店

### ISSUE THREAD

**Issue by NathanIceSea** [wallenweel/weel-translate#35]
这款拓展挺不错的，可惜目前下架了，设备同步后拓展装不上
支持作者

**Comment by wallenweel** [comment]
得先道个歉呢，可能不会太快提交新版本，这次是完全重构打算从底层直接支持构建多个浏览器平台的扩展（试验想法，不过至少新版火狐肯定是没问题的），有更多的工作需要做。

------

想了想还是顺便做点解释吧：

上个版本因为对火狐的安全审核不太了解，同时官方接口还处于发展测试阶段，经常会出现变更，导致扩展反复因为新的审核标准被下架、要求补充资料。而我自己只是业余兴趣，被这么反复折腾确实有些烦心，加之还在学习其它的事情所以就没有精力继续维护下去了。

这次重构扩展也是因为换了电脑后发现 v2 版本被全线下架了，只能安装更老的版本（我连市场的邮件都没有收到……）。

所以，既然打算重新开始就要好好做准备，把能预料到的问题都事先处理掉。不过一年没碰了，也不知道会不会出现新的问题。

还有哦，现在稳定可免费使用的翻译源也少了，这次重构里也被坑了不少次，所以如果最后没有能够发布上线的话，实属无奈，请见谅 😏

**Comment by NathanIceSea** [comment]
了解（笑哭），确实，有道 API 今天理论上正式 GG 了
辛苦了！@wallenweel

**Comment by NathanIceSea** [comment]
> 已重新上架（并不知道会不会又被下掉，webpack 没法一直构建出 sha 值相通的文件，这次只有这个问题了）。
> 新版最初就设计了 api 和爬虫两种方式，不过上架的只是前期测试发布用，只包含了国际和大陆版本的 google 配置文件。

@wallenweel 
不错，赞一个！😄
