### ISSUE TITLE
插件新的图标不是很好看，喜欢原来的图标

### ISSUE THREAD

**Issue by iamsxm** [wallenweel/weel-translate#36]
插件新的图标不是很好看，喜欢原来的图标

**Comment by wallenweel** [comment]
不出意外的话，后续会开放界面定制的功能，到时只要能够自定义的东西都会设计实现。目前只提供了基本默认状态。

最近主要是为了避免像之前一样因为不可控的原因被下架，正在解决构建不出相同的生产代码的问题。v2.0 的所有版本被下架就是因为这个，花了两天时间了还没什么头绪，搞笑的是火狐官方工具对相同文件每次也都没法打包出一样的东西，正在等审核，还被下架的话，更新再多也是白忙呢 😭

**Comment by idk500** [comment]
突然更新浓郁的紫色,吓了一跳

**Comment by wallenweel** [comment]
@idk500 😋 新年新气象嘛~

**Comment by wallenweel** [comment]
到 v3.0.14 为止提供了自定义主色和改用 v2 版的图标
