### ISSUE TITLE
3.0 版本 鼠标划词翻译功能能加回来吗

### ISSUE THREAD

**Issue by zhouchengcom** [wallenweel/weel-translate#38]
3.0 版本 鼠标选中单词，能有直接弹出翻译的 选项吗，现在是弹出翻译图标。

**Comment by wallenweel** [comment]
会在 v3.0.12 加入（平时很少用就给忘了😅

**Comment by wallenweel** [comment]
🎉已在 v3.0.13 中加入（需要关闭 __浮动按钮__ 选项后才可开启）。
